### ISSUE TITLE
Let's enable Qulice profile in the CI/CD.

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/omdb-api#6]
For now, we don't check our code in the Qulice. Needs to implement that.

**Comment by 0pdd** [comment]
@aivinog1 the puzzle [#22](https://github.com/aivinog1/omdb-api/issues/22) is still not solved.

**Comment by aivinog1** [comment]
Todos were created, let's close this.

**Comment by 0pdd** [comment]
@aivinog1 the puzzle [#31](https://github.com/aivinog1/omdb-api/issues/31) is still not solved; solved: [#22](https://github.com/aivinog1/omdb-api/issues/22).
